name: Deploy to AWS

on:
  push:
    branches:
      - main  # Trigger on pushes to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Or your required Node version

    - name: Install dependencies
      run: npm install

    - name: Build Next.js app
      run: npm run build  # This automatically includes the export due to output: 'export'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Replace with your AWS region

    - name: Sync files to S3
      run: |
          cd ./
          aws s3 sync out/ s3://cloud-resume-challenge-yes --delete

    - name: Invalidate CloudFront Cache
      env:
        CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"